# Generated by Django 5.0.3 on 2024-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditions', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
